stages:
- name: 编译
  steps:
  - publishImageConfig:
      dockerfilePath: ./CustomersAPIServices/Dockerfile
      buildContext: .
      tag: apigetway
      pushRemote: true
      registry: 127.0.0.1:34610
timeout: 60
notification: {}
